services:
  zhora-database:
    image: 'pgvector/pgvector:pg17'
    container_name: zhora-database
    hostname: zhora-database
    environment:
      POSTGRES_DB: zhora
      POSTGRES_USER: zhora
      POSTGRES_PASSWORD: zhora
    ports:
      - 15432:5432
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    restart: always

  minio:
    image: bitnami/minio:latest
    user: root
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_BROWSER: on
      MINIO_DEFAULT_BUCKETS: zhora:public
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ~/docker/store/minio/data:/Users/jasonlu/Desktop/lzh/minio