# 环境配置
server:
  servlet:
    # 应用的访问路径
    context-path: /admin
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# Spring配置
spring:
  application:
    name: zhora-admin
  profiles:
    active: @spring.profiles.active@
    include: dynamic-@spring.profiles.active@
  main:
    allow-bean-definition-overriding: true
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台打印 SQL
    map-underscore-to-camel-case: true  # 下划线转驼峰命名
  global-config:
    db-config:
      id-type: auto  # 主键策略（auto=自增，assign_id=雪花ID）
      logic-delete-field: del_flag  # 逻辑删除字段（默认 deleted）
      logic-delete-value: true  # 逻辑删除值
      logic-not-delete-value: false  # 未删除值
  mapper-locations: classpath:mapper/*.xml  # XML 映射文件路径（可选）


# Knife4j 配置
knife4j:
  enable: true  # 开启 Knife4j
  setting:
    language: zh-CN  # 中文界面
    enable-swagger-default: false  # 禁用原生 Swagger UI
# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

springdoc:
  api-docs:
    # 是否开启接口文档
    enabled: true
  swagger-ui:
    # 持久化认证数据
    persistAuthorization: true
  #这里定义了分组，可定义多个，也可以不定义
  group-configs:
    - group: 1.ai模块
      packages-to-scan: com.zhora.admin.controller.ai
    - group: 2.系统模块
      packages-to-scan: com.zhora.admin.controller.system