server:
  port: 9001

spring:
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

#请求和响应日志
langchain4j:
  open-ai:
    chat-model:
      log-requests: true
      log-responses: true

# 日志配置
logging:
  level:
    com.zhora: debug
    org.springframework: warn
