server:
  port: 19001

spring:
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:    # 密码（默认为空）
      timeout: 6000ms  # 连接超时时长（毫秒）
      lettuce:
        pool:
          max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10      # 连接池中的最大空闲连接
          min-idle: 5       # 连接池中的最小空闲连接

# 是否开启redis缓存  true开启   false关闭
zhora:
  redis:
    open: false

#请求和响应日志
langchain4j:
  open-ai:
    chat-model:
      log-requests: true
      log-responses: true

# 日志配置
logging:
  level:
    com.zhora: debug
    org.springframework: info

